-- ============================================
-- PHARMACY INVENTORY & SALES
-- ROLES AND PRIVILEGES
-- ============================================

-- Create common roles
CREATE ROLE C##PHARMACY_ADMIN CONTAINER=ALL;

CREATE ROLE C##PHARMACY_STAFF CONTAINER=ALL;
SELECT role
FROM dba_roles
WHERE role IN (
    'C##PHARMACY_ADMIN',
    'C##PHARMACY_STAFF'
)
ORDER BY role;

------------------------------------------------------------
-- PHARMACY INVENTORY & SALES
-- ROLES AND PRIVILEGES
------------------------------------------------------------

------------------------------------------------------------
-- 1. ADMIN ROLE PRIVILEGES
------------------------------------------------------------

-- ADMIN: Full CRUD access to all pharmacy tables

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.USERS
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.SUPPLIER
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.COMPANY
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.CATEGORY
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.CUSTOMER
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.MEDICINE
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.PURCHASE
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.PURCHASEDETAILS
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.SALES
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.SALESDETAILS
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.STOCKLOG
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;

GRANT SELECT, INSERT, UPDATE, DELETE
ON SYSTEM.EXPIRYALERT
TO C##PHARMACY_ADMIN
CONTAINER=CURRENT;


------------------------------------------------------------
-- 2. STAFF ROLE PRIVILEGES
------------------------------------------------------------

-- STAFF: Can view all pharmacy information

GRANT SELECT
ON SYSTEM.USERS
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.SUPPLIER
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.COMPANY
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.CATEGORY
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.CUSTOMER
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.MEDICINE
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.PURCHASE
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.PURCHASEDETAILS
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.SALES
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.SALESDETAILS
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.STOCKLOG
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT SELECT
ON SYSTEM.EXPIRYALERT
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;


------------------------------------------------------------
-- 3. STAFF: OPERATIONAL INSERT / UPDATE ACCESS
------------------------------------------------------------

-- Customer management

GRANT INSERT, UPDATE
ON SYSTEM.CUSTOMER
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;


-- Purchase processing

GRANT INSERT, UPDATE
ON SYSTEM.PURCHASE
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT INSERT, UPDATE
ON SYSTEM.PURCHASEDETAILS
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;


-- Sales processing

GRANT INSERT, UPDATE
ON SYSTEM.SALES
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;

GRANT INSERT, UPDATE
ON SYSTEM.SALESDETAILS
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;


-- Stock log

GRANT INSERT
ON SYSTEM.STOCKLOG
TO C##PHARMACY_STAFF
CONTAINER=CURRENT;


------------------------------------------------------------
-- END OF TABLE PRIVILEGES
------------------------------------------------------------