-- =============================================================================
-- Al-Dawah Pharma - Pharmacy Inventory & Sales Management System
-- Script: 07_roles_privileges.sql
-- Description: Oracle Roles, Least-Privilege Grants, and Application User Configuration
-- Source of Truth: Oracle Database
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. CREATE COMMON ROLES
-- -----------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE C##PHARMACY_ADMIN CONTAINER=ALL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1921 THEN -- role already exists
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE C##PHARMACY_STAFF CONTAINER=ALL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1921 THEN -- role already exists
            RAISE;
        END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 2. ADMIN ROLE PRIVILEGES (Full CRUD on all tables, views, procedures, functions)
-- -----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON Users TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Supplier TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Company TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Category TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Customer TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Medicine TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Purchase TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PurchaseDetails TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON Sales TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON SalesDetails TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON StockLog TO C##PHARMACY_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ExpiryAlert TO C##PHARMACY_ADMIN;

-- Admin View Privileges
GRANT SELECT ON ExpiredMedicine_View TO C##PHARMACY_ADMIN;
GRANT SELECT ON NearExpiryMedicine_View TO C##PHARMACY_ADMIN;
GRANT SELECT ON LowStock_View TO C##PHARMACY_ADMIN;
GRANT SELECT ON MonthlySales_View TO C##PHARMACY_ADMIN;
GRANT SELECT ON InventoryValue_View TO C##PHARMACY_ADMIN;
GRANT SELECT ON CompanyWiseStock_View TO C##PHARMACY_ADMIN;
GRANT SELECT ON SupplierWisePurchase_View TO C##PHARMACY_ADMIN;

-- Admin Routine Privileges
GRANT EXECUTE ON ADD_CATEGORY TO C##PHARMACY_ADMIN;
GRANT EXECUTE ON ADD_MEDICINE TO C##PHARMACY_ADMIN;
GRANT EXECUTE ON RECORD_PURCHASE TO C##PHARMACY_ADMIN;
GRANT EXECUTE ON RECORD_SALE TO C##PHARMACY_ADMIN;
GRANT EXECUTE ON GET_AVAILABLE_STOCK TO C##PHARMACY_ADMIN;
GRANT EXECUTE ON GET_INVENTORY_VALUE TO C##PHARMACY_ADMIN;

-- -----------------------------------------------------------------------------
-- 3. STAFF ROLE PRIVILEGES (Operational permissions; no drop/delete privileges)
-- -----------------------------------------------------------------------------
-- Read-only access to catalogs and audit logs
GRANT SELECT ON Users TO C##PHARMACY_STAFF;
GRANT SELECT ON Supplier TO C##PHARMACY_STAFF;
GRANT SELECT ON Company TO C##PHARMACY_STAFF;
GRANT SELECT ON Category TO C##PHARMACY_STAFF;
GRANT SELECT ON Medicine TO C##PHARMACY_STAFF;
GRANT SELECT ON StockLog TO C##PHARMACY_STAFF;
GRANT SELECT ON ExpiryAlert TO C##PHARMACY_STAFF;

-- Operational Read/Insert/Update access
GRANT SELECT, INSERT, UPDATE ON Customer TO C##PHARMACY_STAFF;
GRANT SELECT, INSERT, UPDATE ON Purchase TO C##PHARMACY_STAFF;
GRANT SELECT, INSERT, UPDATE ON PurchaseDetails TO C##PHARMACY_STAFF;
GRANT SELECT, INSERT, UPDATE ON Sales TO C##PHARMACY_STAFF;
GRANT SELECT, INSERT, UPDATE ON SalesDetails TO C##PHARMACY_STAFF;
GRANT INSERT ON StockLog TO C##PHARMACY_STAFF;

-- Staff View Privileges
GRANT SELECT ON ExpiredMedicine_View TO C##PHARMACY_STAFF;
GRANT SELECT ON NearExpiryMedicine_View TO C##PHARMACY_STAFF;
GRANT SELECT ON LowStock_View TO C##PHARMACY_STAFF;
GRANT SELECT ON MonthlySales_View TO C##PHARMACY_STAFF;
GRANT SELECT ON InventoryValue_View TO C##PHARMACY_STAFF;
GRANT SELECT ON CompanyWiseStock_View TO C##PHARMACY_STAFF;
GRANT SELECT ON SupplierWisePurchase_View TO C##PHARMACY_STAFF;

-- Staff Routine Privileges (Operational execution)
GRANT EXECUTE ON RECORD_PURCHASE TO C##PHARMACY_STAFF;
GRANT EXECUTE ON RECORD_SALE TO C##PHARMACY_STAFF;
GRANT EXECUTE ON GET_AVAILABLE_STOCK TO C##PHARMACY_STAFF;
GRANT EXECUTE ON GET_INVENTORY_VALUE TO C##PHARMACY_STAFF;

-- -----------------------------------------------------------------------------
-- 4. DEDICATED APPLICATION DATABASE USER (C##PHARMACY_APP)
-- The application connects as C##PHARMACY_APP rather than SYS/SYSTEM
-- -----------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER C##PHARMACY_APP IDENTIFIED BY PharmacyApp2026# CONTAINER=ALL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN -- user already exists
            RAISE;
        END IF;
END;
/

GRANT CONNECT, RESOURCE, CREATE SESSION TO C##PHARMACY_APP CONTAINER=ALL;
GRANT C##PHARMACY_ADMIN TO C##PHARMACY_APP CONTAINER=ALL;
GRANT C##PHARMACY_STAFF TO C##PHARMACY_APP CONTAINER=ALL;

-- Direct routine grants for reliable execution
GRANT EXECUTE ON ADD_CATEGORY TO C##PHARMACY_APP;
GRANT EXECUTE ON ADD_MEDICINE TO C##PHARMACY_APP;
GRANT EXECUTE ON RECORD_PURCHASE TO C##PHARMACY_APP;
GRANT EXECUTE ON RECORD_SALE TO C##PHARMACY_APP;
GRANT EXECUTE ON GET_AVAILABLE_STOCK TO C##PHARMACY_APP;
GRANT EXECUTE ON GET_INVENTORY_VALUE TO C##PHARMACY_APP;

-- -----------------------------------------------------------------------------
-- 5. PUBLIC SYNONYMS
-- Allows application queries without hardcoding the schema owner prefix
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PUBLIC SYNONYM Users FOR SYSTEM.Users;
CREATE OR REPLACE PUBLIC SYNONYM Supplier FOR SYSTEM.Supplier;
CREATE OR REPLACE PUBLIC SYNONYM Company FOR SYSTEM.Company;
CREATE OR REPLACE PUBLIC SYNONYM Category FOR SYSTEM.Category;
CREATE OR REPLACE PUBLIC SYNONYM Customer FOR SYSTEM.Customer;
CREATE OR REPLACE PUBLIC SYNONYM Medicine FOR SYSTEM.Medicine;
CREATE OR REPLACE PUBLIC SYNONYM Purchase FOR SYSTEM.Purchase;
CREATE OR REPLACE PUBLIC SYNONYM PurchaseDetails FOR SYSTEM.PurchaseDetails;
CREATE OR REPLACE PUBLIC SYNONYM Sales FOR SYSTEM.Sales;
CREATE OR REPLACE PUBLIC SYNONYM SalesDetails FOR SYSTEM.SalesDetails;
CREATE OR REPLACE PUBLIC SYNONYM StockLog FOR SYSTEM.StockLog;
CREATE OR REPLACE PUBLIC SYNONYM ExpiryAlert FOR SYSTEM.ExpiryAlert;

CREATE OR REPLACE PUBLIC SYNONYM ExpiredMedicine_View FOR SYSTEM.ExpiredMedicine_View;
CREATE OR REPLACE PUBLIC SYNONYM NearExpiryMedicine_View FOR SYSTEM.NearExpiryMedicine_View;
CREATE OR REPLACE PUBLIC SYNONYM LowStock_View FOR SYSTEM.LowStock_View;
CREATE OR REPLACE PUBLIC SYNONYM MonthlySales_View FOR SYSTEM.MonthlySales_View;
CREATE OR REPLACE PUBLIC SYNONYM InventoryValue_View FOR SYSTEM.InventoryValue_View;
CREATE OR REPLACE PUBLIC SYNONYM CompanyWiseStock_View FOR SYSTEM.CompanyWiseStock_View;
CREATE OR REPLACE PUBLIC SYNONYM SupplierWisePurchase_View FOR SYSTEM.SupplierWisePurchase_View;

CREATE OR REPLACE PUBLIC SYNONYM ADD_CATEGORY FOR SYSTEM.ADD_CATEGORY;
CREATE OR REPLACE PUBLIC SYNONYM ADD_MEDICINE FOR SYSTEM.ADD_MEDICINE;
CREATE OR REPLACE PUBLIC SYNONYM RECORD_PURCHASE FOR SYSTEM.RECORD_PURCHASE;
CREATE OR REPLACE PUBLIC SYNONYM RECORD_SALE FOR SYSTEM.RECORD_SALE;
CREATE OR REPLACE PUBLIC SYNONYM GET_AVAILABLE_STOCK FOR SYSTEM.GET_AVAILABLE_STOCK;
CREATE OR REPLACE PUBLIC SYNONYM GET_INVENTORY_VALUE FOR SYSTEM.GET_INVENTORY_VALUE;
